# Generated by Django 4.2.5 on 2023-10-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registro_paciente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("apellido_paterno", models.CharField(max_length=200)),
                ("apellido_materno", models.CharField(max_length=200)),
                ("genero", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=200)),
                ("edad", models.CharField(max_length=200)),
                ("prueba", models.CharField(max_length=200)),
                ("diagnostico", models.CharField(max_length=200)),
                ("doctor", models.CharField(max_length=200)),
                ("fecha", models.CharField(max_length=200)),
            ],
        ),
    ]
