# Generated by Django 4.2.5 on 2023-10-25 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registro_paciente", "0002_registrodos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RegistroDos",
            new_name="RegistroDosModel",
        ),
    ]
