# Generated by Django 4.2.5 on 2023-11-02 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "registro_paciente",
            "0005_authgroup_authgrouppermissions_authpermission_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistroPacientePruebasmodel",
        ),
        migrations.DeleteModel(
            name="RegistroPacienteRegistrodosmodel",
        ),
        migrations.AlterModelTable(
            name="registro",
            table="registro",
        ),
    ]
