# Generated by Django 4.2.5 on 2023-11-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registro_paciente", "0006_delete_registropacientepruebasmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
